CREATE TABLE IF NOT EXISTS weekly_stats (
    id SERIAL PRIMARY KEY,
    year INT NOT NULL,
    week INT NOT NULL,
    running_km DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    cycling_km DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    swimming_m DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(year, week)
);
