name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-and-lint:
    name: DevSecOps & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nix cache
        uses: cachix/cachix-action@v14
        with:
          name: mystats
          skipPush: true
        continue-on-error: true

      - name: Run code formatting, syntax, and GitLeaks (pre-commit)
        run: nix-shell --run "pre-commit run --all-files"

      - name: Run Dependency Audit and License Check (Cargo Audit & Cargo Deny)
        run: nix-shell --run "just check-security"

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend (Rust)
        run: nix-shell --run "cd backend && cargo build --release"

      - name: Build Frontend (Vue.js)
        run: nix-shell --run "cd frontend && npm install && npm run build"
